In [1]:
import numpy as np
import pandas as pd
import csv
import sklearn.preprocessing as sk
from gensim.corpora import MmCorpus
import time
from gensim.test.utils import get_tmpfile
import gensim
import gensim.models.lsimodel as ls

from sklearn.decomposition import TruncatedSVD
from sklearn.random_projection import sparse_random_matrix
from sklearn.utils.extmath import randomized_svd

In [4]:
ratings_df = pd.read_csv('Books_Data.csv', dtype={'Rating': float})
ratings_df.loc[:,'Rating'] = sk.minmax_scale(ratings_df.loc[:,'Rating'])


R_df = ratings_df.pivot(index = 'User-ID', columns ='Book-ID', values = 'Rating').fillna(0).to_sparse(fill_value=0)
start=time.clock()

R = R_df.as_matrix()
if(np.isinf(R).all()==False):
    print("tr")

Z=gensim.matutils.Dense2Corpus(R, documents_columns=True)
lsi=ls.LsiModel(Z, num_topics=3)
print("Sigma")
print(lsi.projection.s)
print("U")
print(lsi.projection.u)
print("VT")
V = gensim.matutils.corpus2dense(lsi[Z], len(lsi.projection.s)).T / lsi.projection.s
print(V)
print(time.clock() - start)

tr
Sigma
[ 237.07526885  109.19816569  101.01964478]
U
[[ 0.01048426  0.00986909 -0.0176566 ]
 [ 0.00090768  0.00037122 -0.00128431]
 [ 0.0019742   0.0031406  -0.00083702]
 ..., 
 [ 0.0114385  -0.01399668 -0.00102283]
 [ 0.00052063 -0.00072888 -0.00108729]
 [ 0.00860721  0.00607833 -0.00897272]]
VT
[[ 0.0798431  -0.12898014 -0.07924626]
 [ 0.18439808 -0.17604559  0.08793708]
 [ 0.10134031 -0.15523448 -0.09574002]
 ..., 
 [ 0.00072187  0.00061118  0.00162927]
 [ 0.0004477   0.00020714 -0.00075671]
 [ 0.00025503  0.0003691   0.00063215]]
6.688535999999999
